local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TestRunner = require(ReplicatedStorage.Shared.TestFramework.TestRunner)
local Assert = require(ReplicatedStorage.Shared.TestFramework.Assert)
local PlayerDataService = require(game:GetService("ServerScriptService").Services.PlayerDataService)
local suite = { name = "DataSchemaTests", category = "Unit", tests = {} }

table.insert(suite.tests, { name = "default data has required fields", run = function()
    local data = PlayerDataService.DefaultData(123)
    Assert.equals(data.SchemaVersion, 1)
    Assert.equals(data.DNA, 0)
    Assert.equals(data.Fossils, 0)
    Assert.truthy(data.UnlockedSpecies.coelophysis)
    Assert.truthy(data.UnlockedSpecies.parasaurolophus)
    Assert.truthy(data.UnlockedSpecies.utahraptor)
    Assert.truthy(data.UnlockedSpecies.citipati)
    Assert.equals(data.UnlockedSpecies.gallimimus, nil)
    Assert.equals(data.UnlockedSpecies.triceratops, nil)
    Assert.equals(data.UnlockedSpecies.velociraptor, nil)
    Assert.equals(data.UnlockedSpecies.carnotaurus, nil)
    Assert.notNil(data.CosmeticsOwned)
    Assert.notNil(data.EquippedCosmetics)
    Assert.notNil(data.Settings)
    Assert.equals(data.LastPlayedAt, 123)
end })

return TestRunner.registerSuite(suite)
