local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TestRunner = require(ReplicatedStorage.Shared.TestFramework.TestRunner)
local Assert = require(ReplicatedStorage.Shared.TestFramework.Assert)
local SurvivalService = require(game:GetService("ServerScriptService").Services.SurvivalService)
local MockPlayer = require(ReplicatedStorage.Shared.TestFramework.MockPlayer)
local suite = { name = "GrowthLogicTests", category = "Unit", tests = {} }

table.insert(suite.tests, { name = "growth thresholds map to stages and clamp", run = function()
    local player = MockPlayer.new(101, "GrowthTester")
    SurvivalService:CreateState(player, "gallimimus")
    SurvivalService:AddGrowth(player, 25)
    Assert.equals(SurvivalService:GetState(player).GrowthStage, "Juvenile")
    SurvivalService:AddGrowth(player, 25)
    Assert.equals(SurvivalService:GetState(player).GrowthStage, "SubAdult")
    SurvivalService:AddGrowth(player, 25)
    Assert.equals(SurvivalService:GetState(player).GrowthStage, "Adult")
    SurvivalService:AddGrowth(player, 999)
    Assert.equals(SurvivalService:GetState(player).Growth, 100)
end })

table.insert(suite.tests, { name = "death resets life state but not account service", run = function()
    local player = MockPlayer.new(102, "DeathTester")
    SurvivalService:CreateState(player, "gallimimus")
    Assert.truthy(SurvivalService:Kill(player, "test"))
    Assert.truthy(SurvivalService:GetState(player).Dead)
    local state = SurvivalService:Respawn(player)
    Assert.falsy(state.Dead)
    Assert.equals(state.GrowthStage, "Hatchling")
end })

return TestRunner.registerSuite(suite)
