local StoryAssetPlacements = {}

StoryAssetPlacements.ValidationState = "placed_pending_player_angle_review"
StoryAssetPlacements.RequiredVerdict = "player_angle_signed_off"
StoryAssetPlacements.SourceDocument = "docs/assets/current-game-asset-inventory-storyboard.md"

StoryAssetPlacements.BeatRoots = {
    {
        id = "G020_Beat0_Nursery_Hatch",
        name = "Beat0_NurseryHatch",
        displayName = "Hatch At Nursery Grove",
    },
    {
        id = "G020_Beat1_FirstFoodWater",
        name = "Beat1_FirstFoodWater",
        displayName = "First Food And Water",
    },
    {
        id = "G020_Beat4_JungleAmbush",
        name = "Beat4_JungleAmbush",
        displayName = "Jungle Basin Ambush",
    },
    {
        id = "G020_Beat5_SwampDelta_OxygenFish_LiveAssets",
        name = "Beat5_SwampDeltaLiveAssets",
        displayName = "Swamp Delta Live Asset Layer",
    },
    {
        id = "G020_Beat6_RedstoneFossils",
        name = "Beat6_RedstoneFossils",
        displayName = "Redstone Canyon Fossils",
    },
    {
        id = "G020_Beat7_ApocalypticCityMystery",
        name = "Beat7_ApocalypticCityMystery",
        displayName = "Old Eden Mystery",
    },
    {
        id = "G020_Beat8_MountainNesting",
        name = "Beat8_MountainNesting",
        displayName = "Mountain Nesting Loop",
    },
}

StoryAssetPlacements.Placements = {
    {
        name = "Beat0_NurseryEggNest_A",
        beatRoot = "Beat0_NurseryHatch",
        beatId = "G020_Beat0_Nursery_Hatch",
        zone = "NurseryGrove",
        targetFolder = "Nests",
        slot = "beat0.nursery.egg_nest",
        sourceNames = { "Imported_Dinosaur_Egg_Nest", "Imported_Egg_Nest" },
        sourceAssetId = "8895193",
        position = Vector3.new(-1992, 12, 12),
        yawDegrees = -18,
        scale = 0.72,
        category = "Nest",
        fallback = { kind = "Nest", size = Vector3.new(16, 4, 13), color = Color3.fromRGB(126, 92, 57), material = Enum.Material.LeafyGrass },
    },
    {
        name = "Beat1_NurseryStarterFern_A",
        beatRoot = "Beat1_FirstFoodWater",
        beatId = "G020_Beat1_FirstFoodWater",
        zone = "NurseryGrove",
        targetFolder = "BiomeDressing",
        slot = "beat1.food.starter_fern",
        sourceNames = { "G015_Import_cycad_plant", "G030_JungleFernPlant_14703400302", "G014B4_JungleBush" },
        sourceAssetId = "994374738",
        position = Vector3.new(-2034, 12, -48),
        yawDegrees = 32,
        scale = 0.42,
        category = "Fern",
        fallback = { kind = "Plant", size = Vector3.new(10, 5, 10), color = Color3.fromRGB(82, 160, 74), material = Enum.Material.Grass },
    },
    {
        name = "Beat1_NurseryCarcassBones_A",
        beatRoot = "Beat1_FirstFoodWater",
        beatId = "G020_Beat1_FirstFoodWater",
        zone = "NurseryGrove",
        targetFolder = "Nests",
        slot = "beat1.food.carcass_bones",
        sourceNames = { "Imported_CarcassBones_6934081776", "G031_CarnivoreMeatFood", "G014B2_DinoBones" },
        sourceAssetId = "6934081776",
        position = Vector3.new(-1876, 13, -98),
        yawDegrees = 12,
        scale = 0.54,
        category = "Food",
        fallback = { kind = "Bones", size = Vector3.new(9, 2, 5), color = Color3.fromRGB(218, 205, 174), material = Enum.Material.SmoothPlastic },
    },
    {
        name = "Beat4_JungleVineLog_A",
        beatRoot = "Beat4_JungleAmbush",
        beatId = "G020_Beat4_JungleAmbush",
        zone = "JungleBasin",
        targetFolder = "BiomeDressing",
        slot = "beat4.jungle.cover_log",
        sourceNames = { "G014B6_JungleLog", "G015_Import_fallen_tree_log", "G014B4_JungleBush" },
        sourceAssetId = "5380493574",
        position = Vector3.new(-1385, 12, 1038),
        yawDegrees = -42,
        scale = 0.62,
        category = "Vine",
        fallback = { kind = "Log", size = Vector3.new(28, 6, 8), color = Color3.fromRGB(92, 66, 44), material = Enum.Material.Wood },
    },
    {
        name = "Beat4_JungleRuins_A",
        beatRoot = "Beat4_JungleAmbush",
        beatId = "G020_Beat4_JungleAmbush",
        zone = "JungleBasin",
        targetFolder = "Landmarks",
        landmarkFolder = "ElderNestTree",
        slot = "beat4.jungle.ancient_ruins",
        sourceNames = { "G015_Import_ancient_jungle_ruins", "G014B4_AncientRuins", "G014B4_CaveRock" },
        sourceAssetId = "138397836874560",
        position = Vector3.new(-1510, 13, 1118),
        yawDegrees = 24,
        scale = 0.56,
        category = "Landmark",
        fallback = { kind = "Ruin", size = Vector3.new(24, 12, 16), color = Color3.fromRGB(116, 111, 96), material = Enum.Material.Slate },
    },
    {
        name = "Beat5_SwampTreeLog_A",
        beatRoot = "Beat5_SwampDeltaLiveAssets",
        beatId = "G020_Beat5_SwampDelta_OxygenFish_LiveAssets",
        zone = "SwampDelta",
        targetFolder = "BiomeDressing",
        slot = "beat5.swamp_delta.tree_log",
        sourceNames = { "G014B2_SwampLog", "G014B6_RiverRocks" },
        sourceAssetId = "16458140435",
        position = Vector3.new(-235, 9, 1072),
        yawDegrees = 67,
        scale = 0.58,
        category = "SwampTree",
        fallback = { kind = "Log", size = Vector3.new(30, 5, 8), color = Color3.fromRGB(84, 64, 46), material = Enum.Material.Wood },
    },
    {
        name = "Beat5_LilyPad_A",
        beatRoot = "Beat5_SwampDeltaLiveAssets",
        beatId = "G020_Beat5_SwampDelta_OxygenFish_LiveAssets",
        zone = "SwampDelta",
        targetFolder = "BiomeDressing",
        slot = "beat5.swamp_delta.lilypad",
        sourceNames = { "G022_Imported_WaterLily_01", "G014B6_MossPatch" },
        sourceAssetId = "2523657735",
        position = Vector3.new(-116, 10.45, 942),
        yawDegrees = 8,
        scale = 0.48,
        category = "Water",
        fallback = { kind = "Lily", size = Vector3.new(13, 1, 13), color = Color3.fromRGB(82, 144, 76), material = Enum.Material.Grass },
    },
    {
        name = "Beat5_SpinosaurusWake_A",
        beatRoot = "Beat5_SwampDeltaLiveAssets",
        beatId = "G020_Beat5_SwampDelta_OxygenFish_LiveAssets",
        zone = "SwampDelta",
        targetFolder = "BiomeDressing",
        slot = "beat5.swamp_delta.spinosaurus",
        sourceNames = { "Imported_Playable_Spinosaurus_Model_Set", "G033_DinosaurNPCPack_50PlusCandidate" },
        sourceAssetId = "10737775518",
        position = Vector3.new(72, 13, 996),
        yawDegrees = -18,
        scale = 0.34,
        category = "Apex",
        fallback = { kind = "Silhouette", size = Vector3.new(26, 10, 6), color = Color3.fromRGB(54, 72, 62), material = Enum.Material.Slate },
    },
    {
        name = "Beat6_RedstoneArch_A",
        beatRoot = "Beat6_RedstoneFossils",
        beatId = "G020_Beat6_RedstoneFossils",
        zone = "RedstoneCanyon",
        targetFolder = "Landmarks",
        landmarkFolder = "RedstoneArch",
        slot = "beat6.redstone.arch",
        sourceNames = { "G014B6_CanyonArch", "G014B4_DesertRock", "G015_Import_volcano_rocks_lava" },
        sourceAssetId = "96445666021133",
        position = Vector3.new(-245, 20, -548),
        yawDegrees = 88,
        scale = 0.58,
        category = "Cliff",
        fallback = { kind = "Arch", size = Vector3.new(34, 18, 12), color = Color3.fromRGB(156, 83, 54), material = Enum.Material.Sandstone },
    },
    {
        name = "Beat6_RedstoneFossilBones_A",
        beatRoot = "Beat6_RedstoneFossils",
        beatId = "G020_Beat6_RedstoneFossils",
        zone = "RedstoneCanyon",
        targetFolder = "Fossils",
        slot = "beat6.redstone.fossil_bones",
        sourceNames = { "G030_RedstoneFossilBones_137420276606883", "G014B2_DinoBones", "Imported_CarcassBones_6934081776" },
        sourceAssetId = "137420276606883",
        position = Vector3.new(-125, 14, -758),
        yawDegrees = 31,
        scale = 0.34,
        category = "Fossil",
        fallback = { kind = "Bones", size = Vector3.new(16, 3, 9), color = Color3.fromRGB(218, 205, 174), material = Enum.Material.SmoothPlastic },
    },
    {
        name = "Beat7_OldEdenRuin_A",
        beatRoot = "Beat7_ApocalypticCityMystery",
        beatId = "G020_Beat7_ApocalypticCityMystery",
        zone = "ApocalypticCity",
        targetFolder = "Landmarks",
        landmarkFolder = "OldEdenTower",
        slot = "beat7.city.ruin_structure",
        sourceNames = { "G031_CityRuinsStructure", "CodexAssetDrivenSurvivalTemplates", "G014B6_BrokenConcreteWall" },
        sourceAssetId = "509728826",
        position = Vector3.new(620, 14, -86),
        yawDegrees = -12,
        scale = 0.34,
        category = "CityRuin",
        fallback = { kind = "Ruin", size = Vector3.new(34, 18, 22), color = Color3.fromRGB(94, 89, 83), material = Enum.Material.Concrete },
    },
    {
        name = "Beat7_OldEdenWreckedCar_A",
        beatRoot = "Beat7_ApocalypticCityMystery",
        beatId = "G020_Beat7_ApocalypticCityMystery",
        zone = "ApocalypticCity",
        targetFolder = "BiomeDressing",
        slot = "beat7.city.wrecked_car",
        sourceNames = { "Imported_Wrecked_Car", "G014B6_RustyPipes", "G014B6_BrokenConcreteWall" },
        sourceAssetId = "9213436305",
        position = Vector3.new(910, 12, 224),
        yawDegrees = 63,
        scale = 0.58,
        category = "CarWreck",
        fallback = { kind = "Car", size = Vector3.new(16, 6, 9), color = Color3.fromRGB(94, 78, 66), material = Enum.Material.Metal },
    },
    {
        name = "Beat7_OldEdenRoadSign_A",
        beatRoot = "Beat7_ApocalypticCityMystery",
        beatId = "G020_Beat7_ApocalypticCityMystery",
        zone = "ApocalypticCity",
        targetFolder = "BiomeDressing",
        slot = "beat7.city.road_sign",
        sourceNames = { "G014B3_OldRoadSign" },
        sourceAssetId = "87098449723130",
        position = Vector3.new(520, 12, 360),
        yawDegrees = -28,
        scale = 0.68,
        category = "Rubble",
        fallback = { kind = "Sign", size = Vector3.new(8, 11, 3), color = Color3.fromRGB(112, 98, 76), material = Enum.Material.Metal },
    },
    {
        name = "Beat8_MountainNestEggs_A",
        beatRoot = "Beat8_MountainNesting",
        beatId = "G020_Beat8_MountainNesting",
        zone = "MountainNestingCliffs",
        targetFolder = "Nests",
        slot = "beat8.mountain.cliff_eggs",
        sourceNames = { "Imported_Dinosaur_Egg_Nest", "Imported_Egg_Nest" },
        sourceAssetId = "8895193",
        position = Vector3.new(-160, 78, -1608),
        yawDegrees = 18,
        scale = 0.62,
        category = "Nest",
        fallback = { kind = "Nest", size = Vector3.new(18, 4, 14), color = Color3.fromRGB(128, 102, 76), material = Enum.Material.Rock },
    },
    {
        name = "Beat8_MountainCave_A",
        beatRoot = "Beat8_MountainNesting",
        beatId = "G020_Beat8_MountainNesting",
        zone = "MountainNestingCliffs",
        targetFolder = "Landmarks",
        landmarkFolder = "ElderNestTree",
        slot = "beat8.mountain.cave",
        sourceNames = { "G014B4_CaveRock", "G014B6_CanyonArch", "G014B4_DesertRock" },
        sourceAssetId = "139252642326961",
        position = Vector3.new(-75, 78, -1684),
        yawDegrees = 142,
        scale = 0.7,
        category = "Cliff",
        fallback = { kind = "Arch", size = Vector3.new(30, 18, 16), color = Color3.fromRGB(106, 102, 96), material = Enum.Material.Rock },
    },
}

return StoryAssetPlacements
